spring:
  datasource:
    url: jdbc:mysql://106.52.213.83:3306/springboot?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 315A315A
    driver-class-name: com.mysql.jdbc.Driver 
      security:    user:
      name: admin      password: admin
mybatis:  type-aliases-package: com.springboot.domain
  
    
    